"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


PACKAGES = ['pymediainfo']

APP = ['main.py']
APP_NAME = 'Pype Player'
DATA_FILES = []

OPTIONS = {
    'packages': PACKAGES,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': 'Media player with pictures',
        'CFBundleIdentifier': 'com.qt4cpp.osx.pype_player',
        'NSHumanReadableCopyright': 'Copyright  © 2017, Tatsuhiko Ikemoto, All Rights Reserved'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
